Implement reduce
saie100/ood_map_reduce pull request #10
Opened 2023-04-16 12:31 UTC by vnijat93

## Description

[Describe the changes that you've made in this pull request and explain why they are necessary.]

## Checklist

Please ensure that your pull request meets the following requirements:

- [ ] Code compiles without errors and warnings
- [ ] Code follows the project's coding style guidelines
- [ ] Code is tested and test cases pass
- [ ] Code has been reviewed by at least one other developer

## Related Issues

[If your pull request is related to any issues, link them here.]

## Additional Notes

[Include any additional information or notes that may be helpful in reviewing your pull request.]

2023-04-21 04:11 UTC, mcockle23 requested changes

2023-04-21 04:11 UTC, mcockle23 commented on src/Reduce.cpp
> +Reduce::Reduce(string output_dir) { outputDir = output_dir; }
nit: you can use the initializer list syntax instead of assigning the member variable in the constructor.

Reduce::Reduce(string output_dir)
: outputDir{output_dir} {}

2023-04-21 04:11 UTC, mcockle23 commented on src/Reduce.cpp
> +void Reduce::redue(string key, vector<int> intIterator) {
I think this function should be called reduce

2023-04-21 04:11 UTC, mcockle23 commented on src/Reduce.cpp
> +void Reduce::export_result(string key, int value) {}
nit: I prefer camel case - exportResult, but it's up to you

2023-04-21 04:11 UTC, mcockle23 commented on src/Reduce.h
> +  void redue(string key, vector<int> intIterator);
same as in the cpp, rename to reduce.

2023-04-21 04:11 UTC, mcockle23 commented on src/Reduce.cpp
> +void Reduce::export_result(string key, int value) {}
Also, can you create a task in GitHub for integrating the FileManager and implementing the export function?

2023-04-22 12:06 UTC, vnijat93 commented on src/Reduce.cpp
> +Reduce::Reduce(string output_dir) { outputDir = output_dir; }
👍 i always wanted to know how that works. coming from python that syntax confuses me a lot. But its def cleaner than  assigning the member variables

2023-04-24 01:24 UTC, mcockle23 commented on src/Reduce.cpp
> +  string content = key + " : " + to_string(value) + "\n";
this should be in a similar tuple structure as the rest of the class's output "(word,count)"

2023-04-24 01:25 UTC, mcockle23 commented on src/Reduce.cpp
> +  ifstream file(inputFilePath);
this should use filemanager

2023-04-24 01:25 UTC, mcockle23 commented on src/Reduce.cpp
> +
can you add some comments to this function so it's a bit more readable?

2023-04-24 01:25 UTC, mcockle23 commented on src/Workflow.cpp
> +     * FileManager fm = FileManager()
uncomment all this stuff once you have this ready to go.

2023-04-24 01:29 UTC, vnijat93 commented on src/Reduce.cpp
> +  ifstream file(inputFilePath);
I will address it in the next PR

2023-04-24 01:30 UTC, vnijat93 commented
I will address above comments in the next PR

2023-04-24 01:31 UTC, mcockle23 approved these changes

2023-04-24 01:32 UTC, merged