Dave branch
saie100/ood_map_reduce pull request #15
Opened 2023-04-20 02:14 UTC by saie100

## Description

[Describe the changes that you've made in this pull request and explain why they are necessary.]

## Checklist

Please ensure that your pull request meets the following requirements:

- [ ] Code compiles without errors and warnings
- [ ] Code follows the project's coding style guidelines
- [ ] Code is tested and test cases pass
- [ ] Code has been reviewed by at least one other developer

## Related Issues

[If your pull request is related to any issues, link them here.]

## Additional Notes

[Include any additional information or notes that may be helpful in reviewing your pull request.]

2023-04-20 02:39 UTC, vnijat93 requested changes

2023-04-20 02:39 UTC, vnijat93 commented on .pre-commit-config.yaml
> +    - --filter=-build/include_order,-build/header_guard,-build/c++11,-build/namespaces
nit: new line at the end of file

2023-04-20 02:39 UTC, vnijat93 commented on Executive.cpp
> +#include "Executive.h"
move this file to the `src` folder?

2023-04-20 02:39 UTC, vnijat93 commented on Executive.h
> +#ifndef Executive_H
move this file to the headers folder?

2023-04-20 02:39 UTC, vnijat93 commented on Executive.h
> +#endif
nit: add a new line

2023-04-20 02:39 UTC, vnijat93 commented on FileManager.cpp
> +#include "FileManager.h"
move this file to `src` folder

2023-04-20 02:39 UTC, vnijat93 commented on FileManager.h
> +#ifndef FILEMANAGER_H
Move this file to `src` folder

2023-04-20 02:39 UTC, vnijat93 commented on FileManager.h
> +#endif
nit: add a new line

2023-04-20 02:40 UTC, mcockle23 commented on FileManager.cpp
> +  const char* p = path.c_str();
Can you make these variable names a bit more descriptive so they're easier to read?

2023-04-20 02:40 UTC, mcockle23 commented on FileManager.cpp
> +  if (stat(p, &sb) == 0) {
Can you add some comments to these blocks so it's clear what they're doing? This whole file could use some more comments so it's easy to see at a glance what the code is doing.

2023-04-20 02:40 UTC, mcockle23 commented on FileManager.cpp
> +bool FileManager::writeFile(string mode, string output_path, string filename,
Can you update this to be an enum with "WRITE" and "APPEND" as values so we can just pass that constant in instead of a string?

2023-04-20 04:11 UTC, saie100 commented on .pre-commit-config.yaml
> +    - --filter=-build/include_order,-build/header_guard,-build/c++11,-build/namespaces
@vnijat93 What do you mean by "new line at the end of file"?

2023-04-22 13:17 UTC, vnijat93 commented
@mcockle23 recommended using camelcase. We should probably follow that and make things consistent

2023-04-22 14:07 UTC, vnijat93 commented
@saie100 Hey Dave. I have pull your branch and having some thought as i started using your code. I apologize if my comments came across as critical of you or your work. That's not my intention. Happy to chat more and discuss.

2023-04-24 00:21 UTC, mcockle23 approved these changes

2023-04-24 00:34 UTC, vnijat93 approved these changes

2023-04-24 00:34 UTC, merged