Karim2629 patch 3
saie100/ood_map_reduce pull request #17
Opened 2023-04-22 23:13 UTC by karim2629

## Description

[Describe the changes that you've made in this pull request and explain why they are necessary.]

## Checklist

Please ensure that your pull request meets the following requirements:

- [ ] Code compiles without errors and warnings
- [ ] Code follows the project's coding style guidelines
- [ ] Code is tested and test cases pass
- [ ] Code has been reviewed by at least one other developer

## Related Issues

[If your pull request is related to any issues, link them here.]

## Additional Notes

[Include any additional information or notes that may be helpful in reviewing your pull request.]

2023-04-22 23:27 UTC, karim2629 reviewed
updated sort class to be able to pass file names as arguments; sorter.Reduce("input.txt", "out.txt")

2023-04-24 00:52 UTC, vnijat93 commented on Sort.cpp
> +void Sort::Reduce(const string& input_filename, const string& output_filename) {
Rename this function to `sort`

2023-04-24 00:52 UTC, vnijat93 commented on Sort.cpp
> +    ofstream outfile(output_filename);
use `FileManager` to read from files

2023-04-24 00:52 UTC, vnijat93 commented on Sort.h
> +    void Reduce(const std::string& input_filename, const std::string& output_filename);
update the method name here

2023-04-24 01:03 UTC, mcockle23 requested changes

2023-04-24 01:03 UTC, mcockle23 commented on Sort.cpp
> +#include <fstream>
you shouldn't need fstream or iostream since we will use FileManager for file reads and writes

2023-04-24 01:03 UTC, mcockle23 commented on Sort.cpp
> +    ifstream infile(input_filename);
update this to FileManager calls

2023-04-24 01:45 UTC, mcockle23 approved these changes

2023-04-24 01:45 UTC, merged