Implement workflow
saie100/ood_map_reduce pull request #19
Opened 2023-04-24 03:17 UTC by vnijat93

## Description

[Describe the changes that you've made in this pull request and explain why they are necessary.]

## Checklist

Please ensure that your pull request meets the following requirements:

- [ ] Code compiles without errors and warnings
- [ ] Code follows the project's coding style guidelines
- [ ] Code is tested and test cases pass
- [ ] Code has been reviewed by at least one other developer

## Related Issues

[If your pull request is related to any issues, link them here.]

## Additional Notes

[Include any additional information or notes that may be helpful in reviewing your pull request.]

2023-04-24 04:16 UTC, mcockle23 requested changes

2023-04-24 04:16 UTC, mcockle23 commented on src/Workflow.cpp
> +  Sort s;
This will need to be updated once Sort is updated to take the paths in the constructor.

2023-04-24 04:16 UTC, mcockle23 commented on src/Workflow.cpp
> +  s.Reduce(tempMapOutputFilePath, tempSortOutputFilePath);
This will need to be updated to the renamed sort function and no parameters.

2023-04-24 04:16 UTC, mcockle23 commented on src/Reduce.cpp
>    ifstream file(inputFilePath);
Use FileManager

2023-04-25 02:14 UTC, saie100 approved these changes

2023-04-25 02:15 UTC, merged